### ISSUE TITLE
Bug Credential Error "Exception: invalid-credential"

### ISSUE THREAD

**Issue by kaylaereyes** [rkareem2/Clean-Cycle_flutter-app#23]
When I try to log back in, it says there is an invalid-credential, even though the username and password is in the Cloud Firestore.

<img width="479" alt="Screenshot 2024-08-02 at 6 31 26 PM" src="https://github.com/user-attachments/assets/620a042c-cc3b-4753-a7c5-4a2fa413f957">

**Comment by charles-55** [comment]
Fixed error in PR #27.
